Repository Wai-Technologies/raaghu-docs, pull requests merged in 2024-04, with the labels that each got.

#23 Bug 22 : Language > Translation Issue for Keywords
  i18n/en/docusaurus-plugin-content-docs/current/Release Information/Realse Notes.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Tutorials/Getting-Started-Running-Solution.md
Labels: Bug

#25 Task 24 : Update the CLI Command in Raaghu Docs
  i18n/en/docusaurus-plugin-content-docs/current/CLI/CLI.md
  i18n/pt-BR/docusaurus-plugin-content-docs/current/CLI/CLI.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/CLI/CLI.md
Labels: Documentation

#26 Merged Development : Changes Merged from Development to Production
  i18n/en/docusaurus-plugin-content-docs/current/CLI/CLI.md
  i18n/en/docusaurus-plugin-content-docs/current/Release Information/Realse Notes.md
  i18n/pt-BR/docusaurus-plugin-content-docs/current/CLI/CLI.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/CLI/CLI.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Tutorials/Getting-Started-Running-Solution.md
Labels: Enhancement
